### ISSUE TITLE
Bank Account Access Management

### ISSUE THREAD

**Issue by francis-pouatcha** [ADORSYS-GIS/ledgers#1]
The purpose of this epic is to develop a Bank Account Access Management system as part of the Ledgers module. The system will handle access control for bank accounts based on roles and permissions. The access data model will be stored in the Ledgers core banking database, and Keycloak will enforce rules based on the BankAccountAccess resource. This epic will cover the creation of repositories, services, and REST APIs for managing these access entries.

**Subtasks:**
- [ ] ADORSYS-GIS/ledgers#2 
- [ ] ADORSYS-GIS/ledgers#3
- [ ] ADORSYS-GIS/ledgers#8
- [ ] ADORSYS-GIS/ledgers#13 
- [ ] ADORSYS-GIS/ledgers#19 
- [ ] ADORSYS-GIS/ledgers#25 
- [ ] ADORSYS-GIS/ledgers#39 
- [ ] ADORSYS-GIS/ledgers#30 
- [ ] ADORSYS-GIS/ledgers#22 
- [ ] ADORSYS-GIS/ledgers#36 
- [ ] ADORSYS-GIS/ledgers#28 
- [ ] ADORSYS-GIS/webank#47 
- [ ] ADORSYS-GIS/ledgers#23 
- [ ] ADORSYS-GIS/ledgers#34 
- [ ] ADORSYS-GIS/webank#50

**Comment by francis-pouatcha** [comment]
Obsolete
